from typing import Protocol
from app.schemas.market import Candle, MarketSnapshot

class CapabilityNotSupported(RuntimeError):
    pass

class MarketDataProvider(Protocol):
    async def get_historical_candles(self, instrument: str, days: int = 260) -> list[Candle]: ...
    async def get_snapshot(self, instrument: str) -> MarketSnapshot: ...
    async def get_option_chain(self, instrument: str, expiry: str | None = None) -> dict: ...
    async def get_ipos(self, status: str = "open") -> list[dict]: ...
